%
% REPORTOPTIONS  List of all options available in report objects.
%
% 'angle' numeric (-90)
% 'centering' logical (true)
% 'close' logical (true)
% 'colnames' cellstr (empty)
% 'colsep' numeric (0.4)
% 'color' logical (false)
% 'dateformat' char|Inf (Inf)
% 'decimal' numeric (1)
% 'divider' numeric (empty)
% 'equalwidth' logical (true)
% 'bold' logical (false)
% 'fontname' char ('times')
% 'fontsize' char (empty)
% 'footnote' char (empty)
% 'graphvisible' logical (true)
% 'hdivider' numeric (empty)
% 'heading' char (empty)
% 'hframe' logical (true)
% 'horizontal' numeric (3)
% 'inf' char ('$\infty$')
% 'intercolumn' numeric (8)
% 'irisstamp' logical (false)
% 'italic' logical (false)
% 'language' char ('en')
% 'linestretch' numeric (1.1)
% 'nan' char ('$\cdots$')
% 'orientation' char ('landscape')
% 'pagenumber' logical (true)
% 'papersize' char ('a4')
% 'plotbox' numeric ([1.6,1])
% 'range' numeric (empty)
% 'rownames' cellstr (empty)
% 'saveas' char (empty)
% 'scale' numeric (0.90)
% 'smallcaps' logical (false)
% 'sstate' logical (false)
% 'sstatemark' char ('S/S')
% 'text' char (empty)
% 'textscale' numerid ([0.8,0.8])
% 'timestamp' logical (true)
% 'textwidth' numeric (1)
% 'unit' char (empty)
% 'vdivider' numeric (empty)
% 'vframe' (false)
%
% The IRIS Toolbox 2007/05/03. Copyright 2007 Jaromir Benes. <a href="www.iris-toolbox.com">www.iris-toolbox.com</a>