function h = opengraph(fontsize,visible,plotbox)

h = figure();
set(h,...
  'visible',iff(visible,'on','off'),...
  'paperunits','inches',...
  'paperorientation','landscape',...
  'paperposition',[0 0 [7 7].*plotbox],...
  'papersize',[7 7].*plotbox,...
  'position',irisget('figureposition'),...
  'defaultaxesgridlinestyle',':',...
  'defaultaxesylimmode','auto',...
  'defaultlinelinewidth',1,...
  'defaultaxeslinestyleorder','-|--|:',...
  'defaultaxesnextplot','replace',...
  'defaultaxesfontname','times',...
  'defaultaxesfontsize',fontsize...
);

end