function [blk,ctrl,math] = iriskeywords()

blk = {...
   '@variables:transition',...
   '@variables:measurement',...
   '@shocks',...
   '@variables:log',...
   '@parameters',...
   '@substitutions',...
   '@equations:transition',...
   '@equations:measurement',...
   '@dtrends:measurement',...
   '@equations:reporting',...
   '@equations',...
   '@solvefor',...
   '@shocks:transition',...
   '@shocks:measurement',...
   '@links',...
};

ctrl = {...
   '@end','@if','@else','@for','@do','@stop','@allbut','@linear','@input','@include',...
   '@symbolic','@numerical',...
};

math = {...
   '@ln','@log','@exp','@log10','@sqrt','@isinf','@isnan','@cumsum','@cumprod','@sum','@prod','@ttrend'...
};

end