function A = default_()

A.angle = -90;
A.centering = true;
A.close = true;
A.colnames = {};
A.colsep = 0.4;
A.color = false;
A.dateformat = Inf;
A.decimal = 1;
A.divider = [];
A.equalwidth = true;
A.bold = false;
A.fontname = 'times';
A.fontsize = '';
A.footnote = '';
A.graphvisible = true;
A.hdivider = [];
A.heading = '';
A.hframe = true;
A.horizontal = 3;
A.inf = '$\infty$';
A.intercolumn = 8;
A.irisstamp = false;
A.italic = false;
A.language = 'en';
A.linestretch = 1.1;
A.nan = '$\cdots$';
A.orientation = 'landscape';
A.pagenumber = true;
A.papersize = 'a4';
A.plotbox = [1.6,1];
A.range = [];
A.rownames = {};
A.saveas = '';
A.scale = 0.90;
A.smallcaps = false;
A.sstate = false;
A.sstatemark = 'S/S';
A.text = '';
A.textscale = [0.8,0.8];
A.timestamp = true;
A.textwidth = 1;
A.unit = '';
A.vdivider = [];
A.vframe = false;

end